### ISSUE TITLE
TRAIL INFO, COORDINATES, TELEPHONE NUMBER, AND INTEGERS FORMAT ENHANCEMENT - PIEMONTE.HTML

### ISSUE THREAD

**Issue by manuelokoye** [lucabarattini/NEW_REPO_LSPD_BCG#15]
In the CSV file:
- The format in the last three columns shall be integer and not decimal 
- Duplicate entries shall be removed
- If the phone number doesn't have at least 10 digits, replace with "---"

**Comment by lucabarattini** [comment]
Done, work carried out by @manuelokoye
