### ISSUE TITLE
navbar implementation front-end bootstrap

### ISSUE THREAD

**Issue by CebanMi** [lucabarattini/NEW_REPO_LSPD_BCG#4]
Implementing anavbar using bootstrap docs carried out by Mirela and Pietro in HTML

**Comment by lucabarattini** [comment]
The navbar has been moved inside the container that can be found in the page: index.html . 
Moreover, they have also used some classed in order to make it responsive (class="container-fluid mt-5 mb-5").

Work carried out by @CebanMi  and @PietroDiCurzio, well done! Thanks
